

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/HX8527/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+= himax_platform.o 
obj-y	+= himax_852xES.o
